config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, :homes, :books#, :book_issues
  resources :book_issues do
    member do
      get :student
    end
  end
  root "homes#index"
  get 'book_issue/record', to: 'book_issues#record' 
  get 'book_issue/myrecord', to: 'book_issues#myrecord'
  get 'book_issues', to: 'book_issues#index'
  post 'book_issues', to: 'book_issues#create'
  patch 'book_issue', to: 'book_issues#update'
  get 'book_data', to: 'books#book_data'
  get 'hotwire_index', to: 'books#hotwire_index'
  get 'search', to: 'books#search'
  # get 'book_issues/student/:id', to: 'book_issues#student'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # post 'book_issue', to: 'book_issue#create'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :book_issues, :dependent => :destroy
  has_many :books, through: :book_issues
  before_validation :normalize_name, on: :create
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :email, confirmation: true, presence: true
  validates :name, presence: true, length: { minimum: 3, too_short: "must have at least %{count} characters." }
  validates :password, confirmation: true

  def admin?
    type == "Admin"
  end

  def student?
    type == "Student"
  end

  private
    def normalize_name
      self.name = name.downcase.titleize
    end

    # def check_status
    #   BookIssue.find_by(user_id: current_user.id)
    # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def show
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<head>
  <title>Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
 </head>
 <body class="background">
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark container-12">
    <%= image_tag 'logo.jpg', alt: 'logo', width: "65", height: "45" %>
    <div class="container-fluid">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link"<%= link_to "Home", homes_path %>></a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Books", books_path %>></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" <%= link_to "Record", book_issue_record_path %></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" <%= link_to "Requests", book_issues_path %></a>
        </li>
      
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Back", homes_path %>></a>
        </li>
      </ul>
    </div>

    <span class="name"> <%= current_user.name.camelize %> </span>
    <span class="name"> <%= current_user.type.camelize %> </span> 

    <div class="name"> 
      <%= link_to 'Profile', edit_user_registration_path, :class => 'navbar-link' %>
    </div>  
    
    <div class="name">
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Signout", destroy_user_session_path, :method => :delete, :class => 'navbar-link' %></a>
      </li>
    </div>
    
  </nav>
  <div class="book">
    <caption>Student Details</caption>
    <table border="3px" cellpadding="3px" cellspacing="3px">
      <tr>
        <th>Student Name</th>
      </tr>
        <% @users.each do |user| %>
          <tr>
            <td> <%= link_to user.name, book_issue_path(id: user.id), :method => :get %></td>
          </tr>
        <% end %>
      <tr>
    </table>
  </div>
</body>

app/views/users/show.html.erb
<head>
  <title>Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
 </head>
 <body class="background">
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark container-12">
    <%= image_tag 'logo.jpg', alt: 'logo', width: "65", height: "45" %>
    <div class="container-fluid">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link"<%= link_to "Home", homes_path %>></a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Books", books_path %>></a>
        </li>

        <% if current_user.student? %>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "My record", book_issues_path %></a>
          </li>
        <% end %>

        <% if current_user.admin? %>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Record", book_issue_record_path %></a>
          </li>

          <li class="nav-item">
            <a class="nav-link" <%= link_to "Requests", book_issues_path %></a>
          </li>
        <% end %>
      
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Back", homes_path %>></a>
        </li>
      </ul>
    </div>

    <span class="name"> <%= current_user.name.camelize %> </span>
    <span class="name"> <%= current_user.type.camelize %> </span> 
    
    <div class="name"> 
      <%= link_to 'Profile', edit_user_registration_path, :class => 'navbar-link' %>
    </div>  
    
    <div class="name">
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Signout", destroy_user_session_path, :method => :delete, :class => 'navbar-link' %></a>
      </li>
    </div>

  </nav>
</body>