config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, :homes, :books#, :book_issues
  resources :book_issues do
    member do
      get :student
    end
  end
  root "homes#index"
  get 'book_issue/record', to: 'book_issues#record' 
  get 'book_issue/myrecord', to: 'book_issues#myrecord'
  get 'book_issues', to: 'book_issues#index'
  post 'book_issues', to: 'book_issues#create'
  patch 'book_issue', to: 'book_issues#update'
  get 'book_data', to: 'books#book_data'
  get 'hotwire_index', to: 'books#hotwire_index'
  get 'search', to: 'books#search'
  # get 'book_issues/student/:id', to: 'book_issues#student'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # post 'book_issue', to: 'book_issue#create'
end

app/models/book.rb
require 'elasticsearch/model'

class Book < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  searchkick word_start: [:name, :book_author], highlight: [:name]
  has_many :book_issues
  has_many :users, through: :book_issues, :dependent => :destroy
  before_save :normalize_name
  after_commit :reindex_books
  validates :name, presence: true, uniqueness: { scope: :book_author }
  validates :qty, presence: true, length: { minimum: 1 }

  private

  def normalize_name
    self.name = name.downcase.titleize 
    self.book_author = book_author.downcase.titleize
  end

  def reindex_books
    Book.reindex
  end
end

Book.import

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @quantity = 0
    @books = Book.all
    @books.each do |book|
      @quantity += book.qty
    end 
    respond_to do |format|
      format.html
      format.json { render json: BookDatatable.new(params, view_context: view_context) }
    end 
  end

  def new
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def search
    if params[:q].nil?
      @books = []
    else
      @books = Book.search(params[:q], fields: [:name, :book_author], match: :word_start)
      # @books = Book.search params[:q]
    end
  end

  def book_data
    @books = Book.all
  end

  def hotwire_index
    @books = Book.all.order(created_at: :desc)
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    respond_to do |format|
      if @book.save
        format.html { redirect_to books_path }
        format.json { render :show, status: :created, location: @book }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@book, partial: 'posts/form', locals: { post: @book }) }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to hotwire_index_path }
        format.json { render :show, status: :created, location: @book }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@book, partial: 'books/form', locals: { book: @book }) }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

   def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def book_params
      params.require(:book).permit(:name, :book_author, :qty)
    end
end

app/helpers/book_helper.rb
module BookHelper
	class BookDatatable < AjaxDatatablesRails::ActiveRecord
	  extend Forwardable

	  # # either define them one-by-one
	  # def_delegator :@view, :check_box_tag
	  def_delegator :@view, :link_to
	  # def_delegator :@view, :mail_to
	  # def_delegator :@view, :edit_user_path

	  # # or define them in one pass
	  # def_delegators :@view, :check_box_tag, :link_to, :mail_to, :edit_user_path

	  # # ... other methods (view_columns, get_raw_records...)

	  def initialize(params, opts = {})
	    @view = opts[:view_context]
	    super
	  end

	  # now, you'll have these methods available to be used anywhere
	  def data
	    records.map do |record|
	      {
	        id:    check_box_tag('books[]', record.id),
	        name:  record.name,
	        book_author:  record.book_author,
	        qty:   record.qty
	      }
	    end
	  end
	end

	# and in your controller:
	def index
	  respond_to do |format|
	    format.html
	    format.json { render json: BookDatatable.new(params, view_context: view_context) }
	  end
	end
end

app/views/books/_book.html.erb
<div style="background: lightgrey; width: 300px; padding: 5px;">
  <span>Book name : </span>
  <%= book.name %>
  <br>
  <span>Author : </span>
  <%= book.book_author %>
  <br>
  <span>Quantity : </span>
  <%= book.qty %>
  <br>
  <%= link_to :edit, edit_book_path(book), target: :_blank  %>
</div>
<br>

app/views/books/_form.html.erb
<head>
  <title>Edit Book</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body class="background">
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark container-12">
     <%= image_tag 'logo.jpg', alt: 'logo', width: "65", height: "45" %>
    <div class="container-fluid">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link"<%= link_to "Home", homes_path %>></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" <%= link_to "Books", books_path %>></a>
        </li>
      
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Back", homes_path %>></a>
        </li>
      </ul>
    </div>

    <span class="name"> <%= current_user.name.camelize %> </span>
    <span class="name"> <%= current_user.type.camelize %> </span>
    
    <div class="name"> 
      <%= link_to 'Profile', edit_user_registration_path, :class => 'navbar-link' %>
    </div>  
    
    <div class="name">
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Signout", destroy_user_session_path, :method => :delete, :class => 'navbar-link' %></a>
      </li>
    </div>
  </nav>
  <div class="split right">
    <%= form_with model: @book do |form| %>
      <div>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
      </div>

      <div>
        <%= form.label :book_author %><br>
        <%= form.text_field :book_author %>
      </div>

      <div>
        <%= form.label :qty %><br>
        <%= form.number_field :qty %>
      </div>

      <div>
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</body>

app/views/books/book_data.html.erb
<p style="color: green"><%= notice %></p>
<head>
  <title>Books</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
   <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
   <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
</head>
<body class="background">
  <nav class="navbar navbar-fix navbar-expand-sm bg-dark navbar-dark container-12">
     <%= image_tag 'logo.jpg', alt: 'logo', width: "65", height: "45" %>
    <div class="container-fluid">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link"<%= link_to "Home", homes_path %></a>
        </li>
        <% if current_user.admin? %>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Add Book", new_book_path %></a>
          </li>
        <% end %>  
      
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Back", homes_path %></a>
        </li>
      </ul>
    </div>
      <span class="name"> <%= current_user.name.camelize %> </span>
      <span class="name"> <%= current_user.type.camelize %> </span>

    <div class="name"> 
      <%= link_to 'Profile', edit_user_registration_path, :class => 'navbar-link' %>
    </div>  
    
    <div class="name">
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Signout", destroy_user_session_path, :method => :delete, :class => 'navbar-link' %></a>
      </li>
    </div>
  </nav>

  <div id="users">
    <table id="my-table">
      <thead>
        <tr>
          <th>Book Name</th>
          <th>Author Name</th>
          <th>Quantity</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td><%= book.name %></td>
            <td><%= book.book_author %></td>
            <td><%= book.qty %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</body>

app/views/books/edit.html.erb
<%= render "form", books: @book %>

app/views/books/hotwire_index.html.erb
<%= turbo_stream_from :books %>

<%= turbo_frame_tag :book_form do %>
  <%= render 'books/form', book: @book %>
<% end %>

<%= turbo_frame_tag :books do %>
  <%= render @books %>
<% end %>

app/views/books/index.html.erb
<head>
  <title>Books</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
 </head>
 <body class="background">
  <nav class="navbar navbar-fix navbar-expand-sm bg-dark navbar-dark container-12">
     <%= image_tag 'logo.jpg', alt: 'logo', width: "65", height: "45" %>
    <div class="container-fluid">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link"<%= link_to "Home", homes_path %></a>
        </li>
        <% if current_user.admin? %>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Add Book", new_book_path %></a>
          </li>
        <% end %>  
      
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Back", homes_path %></a>
        </li>
      </ul>
    </div>
    
      <span class="name"> <%= current_user.name.camelize %> </span>
      <span class="name"> <%= current_user.type.camelize %> </span>

    <div class="name"> 
      <%= link_to 'Profile', edit_user_registration_path, :class => 'navbar-link' %>
    </div>  
    
    <div class="name">
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Signout", destroy_user_session_path, :method => :delete, :class => 'navbar-link' %></a>
      </li>
    </div>

  </nav>
  <div class="book">
    <caption>Books Details</caption>
    <table border="3px" cellpadding="3px" cellspacing="3px">
      <tr>
        <th>Book Name</th>
        <th>Book Author</th>
        <% if current_user.admin? %>
          <th>Book Quantity</th>
        <% end %>  
        <% if current_user.student? %>
          <th>Book Availability</th>
          <th>Book issue request</th>
        <% end %>  
      </tr>
      <% if current_user.admin? %>
        <% @books.each do |book| %>
          <tr>
            <td><abbr title="click for edit and delete the book"><b> <%= link_to book.name, book %> </b></abbr></td>
            <td> <%= book.book_author %> </td>
            <td> <%= book.qty %> </td>
          </tr>
        <% end %>
        <tr>
          <td colspan="2">Total</td>
          <td> <%= @quantity %> </td>
        </tr>
      <% end %>
      <% if current_user.student? %>
        <% @books.each do |book| %>
          <tr>
            <td> <%= book.name %> </td>
            <td> <%= book.book_author %> </td>
            <% if book.qty >= 1 %>
              <td class="avail"> Available </td>
              <td> <%= button_to "request", book_issues_path(book_id: book.id, user_id: current_user.id), :method => :post %>  </td>
            <% else %>
              <td class="notavail">Not Available </td> 
            <% end %>  
          </tr>
        <% end %> 
      <% end %>   
    </table>
  </div>
</body>

app/views/books/new.html.erb
<%= render "form", books: @book %>

app/views/books/search.html.erb
<head>
  <title>Books</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body class="background">
  <nav class="navbar navbar-fix navbar-expand-sm bg-dark navbar-dark container-12">
     <%= image_tag 'logo.jpg', alt: 'logo', width: "65", height: "45" %>
    <div class="container-fluid">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Back", homes_path %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link"<%= link_to "Home", homes_path %></a>
        </li>
        <% if current_user.admin? %>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Add Book", new_book_path %></a>
          </li>
        <% end %>  
      
      <div class="search">
        <%= form_for search_path, method: :get do |f| %>
          <span>
            <a class="nav-link">
              <%= f.label "Search for" %>
              <%= text_field_tag :q, params[:q] %>
              <%= submit_tag "Go", name: nil %>
            </a>
          </span>
        <% end %>
      </div>
      </ul>
    </div>
    
      <span class="name"> <%= current_user.name.camelize %> </span>
      <span class="name"> <%= current_user.type.camelize %> </span>

    <div class="name"> 
      <%= link_to 'Profile', edit_user_registration_path, :class => 'navbar-link' %>
    </div>  
    
    <div class="name">
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Signout", destroy_user_session_path, :method => :delete, :class => 'navbar-link' %></a>
      </li>
    </div>
  </nav>
  <div>
    <ul>
      <% @books.each do |book| %>
        <li>
          <h3>
            <%= link_to book.name, controller: "books", action: "show", id: book.id%>
          </h3>
        </li>
      <% end %>
    </ul>
  </div>
</body>

app/views/books/show.html.erb
<head>
  <title>New Book</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
 </head>
 <body class="background">
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark container-12">
     <%= image_tag 'logo.jpg', alt: 'logo', width: "65", height: "45" %>
    <div class="container-fluid">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link"<%= link_to "Home", homes_path %></a>
        </li>

        <li class="nav-item">
          <a class="nav-link"<%= link_to "Edit", edit_book_path(@book) %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link"<%= link_to "Destroy", book_path(@book), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } %>></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" <%= link_to "Books", books_path %></a>
        </li>
      
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Back", books_path %></a>
        </li>
      </ul>
    </div>

    <span class="name"> <%= current_user.name.camelize %> </span>
    <span class="name"> <%= current_user.type.camelize %> </span> 
    
    <div class="name"> 
      <%= link_to 'Profile', edit_user_registration_path, :class => 'navbar-link' %>
    </div>  
    
    <div class="name">
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Signout", destroy_user_session_path, :method => :delete, :class => 'navbar-link' %></a>
      </li>
    </div>

  </nav>
  <h1><%= @book.name %></h1>
  <p><b><%= @book.book_author %></b></p>
  <p><b><%= @book.qty %></b></p>
</body>