config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, :homes, :books#, :book_issues
  resources :book_issues do
    member do
      get :student
    end
  end
  root "homes#index"
  get 'book_issue/record', to: 'book_issues#record' 
  get 'book_issue/myrecord', to: 'book_issues#myrecord'
  get 'book_issues', to: 'book_issues#index'
  post 'book_issues', to: 'book_issues#create'
  patch 'book_issue', to: 'book_issues#update'
  get 'book_data', to: 'books#book_data'
  get 'hotwire_index', to: 'books#hotwire_index'
  get 'search', to: 'books#search'
  # get 'book_issues/student/:id', to: 'book_issues#student'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # post 'book_issue', to: 'book_issue#create'
end

app/models/book_issue.rb
class BookIssue < ApplicationRecord
  belongs_to :user
  belongs_to :book
  enum :status, [:request, :allot, :cancel, :return, :deposit]
  before_save :check_status
  validates :book_id, presence: true#, uniqueness: { scope: :user_id if status: != "deposit"}
  # attr_accessor :status

#   before_save :check_status
#   private

  def check_status
    if self.status == "allot"
      @book = Book.find(self.book_id)
      qty = @book.qty
      @book.update(qty: qty-1)
    elsif self.status == "deposit"
      @book = Book.find(self.book_id)
      qty = @book.qty
      @book.update(qty: qty+1)
    end 
  end
end

app/controllers/book_issue_controller.rb
class BookIssueController < ApplicationController
  def index
    @book_issues = BookIssue.all
  end

  # def show
  #   @book_issue_issue = BookIssue.find(params[:id])
  # end
  
  def new
    @book_issue = BookIssue.new
  end

  def create
    @book_issue = BookIssue.new(book_issue_params)

    if @book_issue.save
      redirect_to @book_issue
    else
      render :new, status: :unprocessable_entity
    end
  end

  # def edit
  #   @book_issue = BookIssue.find(params[:id])
  # end

  # def update
  #   @book_issue = BookIssue.find(params[:id])

  #   if @book_issue.update(book_issue_params)
  #     redirect_to @book_issue
  #   else
  #     render :edit, status: :unprocessable_entity
  #   end
  # end

  #  def destroy
  #   @book_issue = BookIssue.find(params[:id])
  #   @book_issue.destroy

  #   redirect_to root_path, status: :see_other
  # end

  # private
  #   def book_issue_params
  #     params.require(:book_issue).permit(:book_name, :author, :qty, :status)
  #   end
end

app/controllers/book_issues_controller.rb
class BookIssuesController < ApplicationController
  def index
    @book_issues = BookIssue.where(status: [0,3])
  end

  def record
    @book_issues = BookIssue.where(status: [1,2,4])
  end

  
  def myrecord
    @myrecords = BookIssue.where(user_id: current_user.id)
  end

  def student
    @student = BookIssue.where(user_id: params[:id])
  end  

  # def new
  #   @book_issue = BookIssue.new(user_id: current_user.id, book_id: params[:id])
  # end

  def create
    @book_issue = BookIssue.new(book_issue_params)
    if @book_issue.save
      redirect_to books_path
      flash.notice = "Book Issue request Successfully created."
    else
      flash.alert = @book_issue.errors.messages
      redirect_to books_path
    end
  end

  # def edit
  #   @book_issue = BookIssue.find(params[:id])
  # end

  def update
    @book_issue = BookIssue.find(params[:id])
    updation = @book_issue.update(status: params[:status])
    if updation
      redirect_back(fallback_location: root_path) 
      flash.notice = "status changed"
    else
      flash.alert = @book_issue.errors.messages
      redirect_to homes_path
    end 
  end

  #  def destroy
  #   @book_issue = BookIssue.find(params[:id])
  #   @book_issue.destroy

  #   redirect_to root_path, status: :see_other
  # end

  private
    def book_issue_params
      params.permit( :user_id, :book_id)
    end
end

app/helpers/book_issue_helper.rb
module BookIssueHelper
end

app/views/book_issues/index.html.erb
<head>
  <title>Requests</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
 </head>
 <body class="background">
  <nav class="navbar navbar-fix navbar-expand-sm bg-dark navbar-dark container-12">
     <%= image_tag 'logo.jpg', alt: 'logo', width: "65", height: "45" %>
    <div class="container-fluid">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link"<%= link_to "Home", homes_path %></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" <%= link_to "Books", books_path %></a>
        </li>

        <% if current_user.admin? %>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Add Book", new_book_path %></a>
          </li>

          <li class="nav-item">
            <a class="nav-link" <%= link_to "Record", book_issue_record_path %></a>
          </li>
        <% end %>  
      
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Back", homes_path %></a>
        </li>
      </ul>
    </div>
    
    <span class="name"> <%= current_user.name.camelize %> </span>
    <span class="name"> <%= current_user.type.camelize %> </span>

    <div class="name"> 
      <%= link_to 'Profile', edit_user_registration_path, :class => 'navbar-link' %>
    </div>
    
    <div class="name">
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Signout", destroy_user_session_path, :method => :delete, :class => 'navbar-link' %></a>
      </li>
    </div>
  </nav>
  <div class="book">
    <caption>Book Issues Details</caption>
    <table border="3px" cellpadding="3px" cellspacing="3px">
      <tr>
        <th>Book Name</th>
        <th>Author Name</th>
        <th>User Name</th>
        <th>Status</th>
      </tr>
        <% @book_issues.each do |data| %>
          <tr>
            <td> <%= Book.find(data.book_id).name  %> </td>
            <td> <%= Book.find(data.book_id).book_author %> </td>
            <td> <%= User.find(data.user_id).name %> </td>
            <td> <%= data.status %> </td>
            <% if data.status == "request" %>
              <td> <%= button_to "allot", book_issue_path(:id => data.id, :status => 'allot'), :method => :patch %> </td>
              <td> <%= button_to "cancel", book_issue_path(:id => data.id, :status => 'cancel'), :method => :patch %> </td>
            <% end %>
            <% if data.status == "return" %>
              <td> <%= button_to "deposit", book_issue_path(:id => data.id, :status => 'deposit'), :method => :patch %> </td>
            <% end %>  
          </tr>
        <% end %>  
    </table>
  </div>
</body>

app/views/book_issues/myrecord.html.erb
<head>
  <title>Requests</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
 </head>
 <body class="background">
  <nav class="navbar navbar-fix navbar-expand-sm bg-dark navbar-dark container-12">
     <%= image_tag 'logo.jpg', alt: 'logo', width: "65", height: "45" %>
    <div class="container-fluid">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link"<%= link_to "Home", homes_path %></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" <%= link_to "Books", books_path %></a>
        </li>
      
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Back", homes_path %></a>
        </li>
      </ul>
    </div>
    
    <span class="name"> <%= current_user.name.camelize %> </span>
    <span class="name"> <%= current_user.type.camelize %> </span>

    <div class="name"> 
      <%= link_to 'Profile', edit_user_registration_path, :class => 'navbar-link' %>
    </div>
    
    <div class="name">
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Signout", destroy_user_session_path, :method => :delete, :class => 'navbar-link' %></a>
      </li>
    </div>
  </nav>
  <div class="book">
    <caption>Book Issues Details</caption>
    <table border="3px" cellpadding="3px" cellspacing="3px">
      <tr>
        <th>Book Name</th>
        <th>Author Name</th> 
        <th>Status</th>
      </tr>
        <% @myrecords.each do |data| %>
          <tr>
            <td> <%= Book.find(data.book_id).name  %> </td>
            <td> <%= Book.find(data.book_id).book_author %> </td>
            <td> <%= data.status %> </td>
            <% if data.status == "allot" %>
              <td> <%= button_to "return", book_issue_path(:id => data.id, :status => 'return'), :method => :patch %> </td>
            <% end %>
          </tr>
        <% end %>  
    </table>
  </div>
</body>

app/views/book_issues/record.html.erb
<head>
  <title>Issue</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
 </head>
 <body class="background">
  <nav class="navbar navbar-fix navbar-expand-sm bg-dark navbar-dark container-12">
     <%= image_tag 'logo.jpg', alt: 'logo', width: "65", height: "45" %>
    <div class="container-fluid">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link"<%= link_to "Home", homes_path %></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" <%= link_to "Books", books_path %></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" <%= link_to "Requests", book_issues_path %></a>
        </li>
      
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Back", :back %></a>
        </li>
      </ul>
    </div>
    
      <span class="name"> <%= current_user.name.camelize %> </span>
      <span class="name"> <%= current_user.type.camelize %> </span>
    
    <div class="name"> 
      <%= link_to 'Profile', edit_user_registration_path, :class => 'navbar-link' %>
    </div>  
    
    <div class="name">
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Signout", destroy_user_session_path, :method => :delete, :class => 'navbar-link' %></a>
      </li>
    </div>
  </nav>
  <div class="book">
    <caption><b>Book Issues Details</b></caption>
    <table border="3px" cellpadding="3px" cellspacing="3px">
      <tr>
        <th>Book Name</th>
        <th>Author Name</th>
        <th>User Name</th>
        <th>Status</th>
      </tr>
        <% @book_issues.each do |data| %>
            <tr>
              <td> <%= Book.find(data.book_id).name  %> </td>
              <td> <%= Book.find(data.book_id).book_author %> </td>
              <td><b> <%= link_to User.find(data.user_id).name, student_book_issue_path(:id => data.user_id), :action => :student, :method => :get, :remote => true %> </b></td>
              <td> <%= data.status %> </td>
            </tr>
        <% end %>
    </table>
  </div>
</body>

app/views/book_issues/show.html.erb
<head>
  <title></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
 </head>
 <body class="background">
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark container-12">
     <%= image_tag 'logo.jpg', alt: 'logo', width: "65", height: "45" %>
    <div class="container-fluid">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link"<%= link_to "Home", homes_path %></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" <%= link_to "Books", books_path %></a>
        </li>
      
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Back", books_path %></a>
        </li>
      </ul>
    </div>

    <span class="name"> <%= current_user.name.camelize %> </span>
    <span class="name"> <%= current_user.type.camelize %> </span> 
    
    <div class="name"> 
      <%= link_to 'Profile', edit_user_registration_path, :class => 'navbar-link' %>
    </div>  
    
    <div class="name">
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Signout", destroy_user_session_path, :method => :delete, :class => 'navbar-link' %></a>
      </li>
    </div>

  </nav>
  <div class="book">
    <caption>Book Issues Details</caption>
    <table border="3px" cellpadding="3px" cellspacing="3px">
      <tr>
        <th>Book Name</th>
        <th>Author Name</th>
        <th>User Name</th>
        <th>Status</th>
      </tr>
        <% @book_issues.each do |data| %>
          <% if data.status == "allot" || data.status == "deposit" || data.status == "cancel" %>
            <tr>
              <td> <%= Book.find(data.book_id).name  %> </td>
              <td> <%= Book.find(data.book_id).book_author %> </td>
              <td> <%= User.find(data.user_id).name %> </td>
              <td> <%= data.status %> </td>
            </tr>
          <% end %>  
        <% end %>
    </table>
  </div>
</body>

app/views/book_issues/student.html.erb
<head>
  <title>Issue</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
 </head>
 <body class="background">
  <nav class="navbar navbar-fix navbar-expand-sm bg-dark navbar-dark container-12">
     <%= image_tag 'logo.jpg', alt: 'logo', width: "65", height: "45" %>
    <div class="container-fluid">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link"<%= link_to "Home", homes_path %></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" <%= link_to "Books", books_path %></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" <%= link_to "Requests", book_issues_path %></a>
        </li>
      
        <li class="nav-item">
          <a class="nav-link" <%= link_to "Back", :back %></a>
        </li>
      </ul>
    </div>
    
      <span class="name"> <%= current_user.name.camelize %> </span>
      <span class="name"> <%= current_user.type.camelize %> </span>
    
    <div class="name"> 
      <%= link_to 'Profile', edit_user_registration_path, :class => 'navbar-link' %>
    </div>  
    
    <div class="name">
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Signout", destroy_user_session_path, :method => :delete, :class => 'navbar-link' %></a>
      </li>
    </div>
  </nav>
  <div class="book">
    <caption>Book Issues Details</caption>
    <table border="3px" cellpadding="3px" cellspacing="3px">
      <tr>
        <th>Book Name</th>
        <th>Author Name</th>
        <th>User Name</th>
        <th>Status</th>
        <th>Created_at</th>
        <th>Days</th>
      </tr>
        <% @student.each do |data| %>
          <tr>
            <td> <%= Book.find(data.book_id).name  %> </td>
            <td> <%= Book.find(data.book_id).book_author %> </td>
            <td> <%= User.find(data.user_id).name %> </td>
            <td> <%= data.status %> </td>
            <td> <%= data.created_at.to_date %> </td>
            <td> <%= ((Time.now - data.created_at)/86400).to_i %> days</td>
          </tr>
        <% end %>
    </table>
  </div>
</body>